# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:

    adapters:
        aws_flysystem_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_BUCKET_NAME)%'
                prefix: IMGS

        public_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public/patient_files/IMGS'
        
         



    filesystems:
        pat_imgs_fs:
            adapter: aws_flysystem_adapter
            mount: pat_imgs_fs

        public_imgs_fs:
            adapter: public_uploads_adapter
            mount: public_imgs_fs
            alias: League\Flysystem\Flysystem
