# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:

    adapters:
    
        aws_flysystem_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_BUCKET_NAME)%'
                prefix: IMGS

        public_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public/store/patient_files/IMGS'
        
        public_user_docs_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public/store/user_files/DOCS'
        

    filesystems:

        pat_imgs_fs:
            adapter: aws_flysystem_adapter
            mount: pat_imgs_fs

        public_imgs_fs:
            adapter: public_uploads_adapter
            mount: public_imgs_fs
            alias: League\Flysystem\Flysystem

        public_user_docs_fs:
            adapter: public_user_docs_uploads_adapter
            mount: public_user_docs_fs
            alias: League\Flysystem\FlysystemUserDocs
