vich_uploader:
    db_driver: orm

    mappings:
        patient_files:
            uri_prefix: /uploads/resources
            upload_destination: '%kernel.project_dir%/public/uploads/resources'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
