vich_uploader:
    db_driver: orm

    mappings:

        patient_files:
            uri_prefix: /uploads/patient_files
            upload_destination: '%kernel.project_dir%/public/uploads/patient_files'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        user_files:
            uri_prefix: /uploads/user_files
            upload_destination: '%kernel.project_dir%/public/uploads/user_files'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
