vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:

        #pat_imgs:
        pat_private_imgs:

            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_BUCKET_NAME)%/IMGS"
            upload_destination: pat_imgs_fs
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        pat_imgs:
        #pat_public_imgs:

            uri_prefix: /store/patient_files/IMGS
            upload_destination: public_imgs_fs
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true



        user_files:
            uri_prefix: /store/user_files/DOCS
            upload_destination: public_user_docs_fs
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

